### ISSUE TITLE
Always show at least one pixel for plotting

### ISSUE THREAD

**Issue by dwhswenson** [dwhswenson/contact_map#48] opened 2019-03-15 13:29 UTC
It is currently possible (especially for atom-atom plots) for the size of one contact to be smaller than a single pixel. The result is that many contacts aren't actually shown. This is very misleading.

We should update the contact object plot such that the dimensions of the patch is guaranteed to be at least 1 pixel. Currently it gives 1 unit on the axis; we need to figure out how many units on the axis correspond to 1 pixel (via matplotlib's resolution).

I think it is fine if we slightly overestimate; this will be a min function, so it will still give a distance of 1 pixel if `pixel_per_axis_unit` > 1.

**Comment by sroet** [comment] 2019-03-18 08:51
> I think it is fine if we slightly overestimate; this will be a min function, so it will still give a distance of 1 axis unit if axis_per_pixel > 1.

shouldn't this be "still give a distance of 1 pixel"?

**Comment by dwhswenson** [comment] 2019-03-19 22:48
> shouldn't this be "still give a distance of 1 pixel"?

Corrected in edited text.

**Comment by sroet** [comment] 2019-03-22 09:10
> `if pixel_per_axis_unit` > 1

this should be smaller than (<) 1, right?

**Comment by sroet** [comment] 2019-03-30 14:08
I have been looking into this, but I can not reproduce the problem when saving to a PDF

In the branch: https://github.com/sroet/contact_map/tree/always_1_pixel, I have added the `**kwargs` argument to `plot()` which passes through to matplotlib. 

there is no difference between the pdf saved from a `dpi=200` and a `dpi=50` plot.
[atoms.pdf](https://github.com/dwhswenson/contact_map/files/3025503/atoms.pdf)
[atoms2.pdf](https://github.com/dwhswenson/contact_map/files/3025504/atoms2.pdf)

Now, there is a difference between the plots if they are saved to `png`:
![atoms.png](https://user-images.githubusercontent.com/19587267/55277068-32430500-52fc-11e9-86dc-082a4bbb094b.png)
![atoms2.png](https://user-images.githubusercontent.com/19587267/55277071-33743200-52fc-11e9-92d9-8b06681350d2.png)

but this is fixed if  `dpi=200` argument is passed to `plt.savefig()`
![atoms3](https://user-images.githubusercontent.com/19587267/55277186-84d0f100-52fd-11e9-8cbc-2f1d1e1690d3.png)


So this looks a lot like this is a compression during the rendering from matplotlib, however I will try to see if I can fix that.

**Comment by dwhswenson** [comment] 2019-03-30 15:09
I'm not surprised that PDF works. I suspect that matplotlib saves the actual postscript commands to draw the figure, which includes all the information (and allows rescaling as a vector format). It shouldn't be DPI-dependent. You'll probably also notice that the files grow with the number of contacts, not the DPI (whereas the opposite will be true for PNG).

Based on what you're seeing, I think the solution here will be to tell users that they need to set the DPI sufficiently high to see everything, or to recommend using PDF output. Note that there is (I think) a way to get PDF output in the notebook, instead of PNG. You can do this with a config setting, or by importing something from `IPython.display`: https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.set_matplotlib_formats

Maybe this is all worth some additional comments in the docs? Not sure where to put it, but maybe it would be best to have a separate rst file to provide the details (a little more information, but based on that link to the IPython docs), and then to link to that from within the examples. That way it doesn't distract from the flow of the example, but the user can figure out why their plots don't look like ours. My first intuition is to place it as a preface to the examples, something like "Recommended Settings" (giving room to add more section later, if needed). If something else makes more sense to you, feel free to try it out (just remember that Sphinx actually writes a book, not a website, so it needs to fit somewhere in a linear order.)

BTW, I hadn't thought about this until I looked at those PDFs, but is the sparsity is because the map is over all atoms, but the contacts are only for heavy atoms? This may be why you see vertical/horizontal linear clusters:
![image](https://user-images.githubusercontent.com/8178546/55277380-cb274f80-52ff-11e9-863b-5094b27df5c7.png)

Also, my browser does a great job of showing the results we'd like when I zoom out to shrink the size of the pdf:
![image](https://user-images.githubusercontent.com/8178546/55277577-21958d80-5302-11e9-8f4f-ea05a8f489c2.png)

**Comment by sroet** [comment] 2019-03-30 15:47
Alright, so it seems like we have to choose between two evils here:

1.  Keep the previous behavior but allow `**kwargs` to be passed through so users can set their `dpi` or `figsize` and maybe raise a `Warning`.
2. The fix, which means that if the initial plot is made with a to low amount of pixels, all the saved figures become 'bad' (even in pdf/png saved at higher resolution).

These are the figures with the new options: (I actually needed to go to 300 dpi to not scale the pixels for a 10x10 inch figure)
pdf plotted with `dpi=300`
[atoms_new.pdf](https://github.com/dwhswenson/contact_map/files/3025643/atoms_new.pdf)
pdf plotted with `dpi=50`
[atoms2_new.pdf](https://github.com/dwhswenson/contact_map/files/3025644/atoms2_new.pdf)

png plotted with `dpi=300`
![atoms_new](https://user-images.githubusercontent.com/19587267/55278188-50fbc880-5309-11e9-8d2f-85e73ff7e205.png)

png plotted with `dpi=50` and saved directly:
![atoms2_new](https://user-images.githubusercontent.com/19587267/55278207-8f918300-5309-11e9-8759-dcf022f4ff3f.png)

png plotted with `dpi=50` but saved with `dpi=300`
![atoms3_new](https://user-images.githubusercontent.com/19587267/55278221-b059d880-5309-11e9-8e9d-2a37474aea57.png)

> BTW, I hadn't thought about this until I looked at those PDFs, but is the sparsity is because the map is over all atoms, but the contacts are only for heavy atoms? This may be why you see vertical/horizontal linear clusters

It looks like it (looking at the real all atom contact map)
[all_atoms.pdf](https://github.com/dwhswenson/contact_map/files/3025661/all_atoms.pdf)

**Comment by dwhswenson** [comment] 2019-03-30 16:50
The main goal here is to prevent a user from misinterpreting a contact map plot. So we don't want the maps to be misleading if you zoom in on them.

Therefore, I think the first approach (allowing the user to pass arbitrary `**kwargs`) is by far the lesser evil -- it may even allow other benefits. I think an additional warning if the `dpi` is likely to lead to degraded images would also be good. This warning should definitely appear if the user manually sets a too-low `dpi`, and maybe should appear if the the default `dpi` is too low. (The warning message should emphasize the need to use a vector output format).

We should combine this with a strong recommendation in the docs that they use vector-based formats, especially for the output of atom contacts (explaining why), and provide some docs on how to do that in a notebook. Most of the details of this would probably be outside the example notebook, but it just requires writing up a brief description of the issues.

**Comment by sroet** [comment] 2019-04-12 14:58
closed by merging of #50

**Closed by sroet** 2019-04-12 14:58 UTC
