### ISSUE TITLE
how to extract some special contacts

### ISSUE THREAD

**Issue by wayuer19** [dwhswenson/contact_map#127] opened 2023-06-22 13:47 UTC
Hi,

I'm trying to calculate the contact map related to helical structure. I first got the contacts from ContactTrajectory, and then tried to delete the items whose residues were not helical. But it doesn't work. Here is the part of my script:
```
contacts = ContactTrajectory(traj)
for i in range(nframe):
    pairs = contacts[i].residue_contacts.most_common()
    hels = dssp[i]     # information of residue helicity
    for idx, pair in enumerate(pairs):
        r1, r2 = pair[0][0], pair[0][1]
        if not (hels[r1.index] == 'H' and hels[r2.index] == 'H'):
            del contacts[i].residue_contacts.most_common()[idx]
```

I think I had some misunderstanding here. Any suggestions?
Thank you so much!

**Comment by sroet** [comment] 2023-06-22 15:53
Hey,

the issue is that every time that you call `contacts[i].residue_contacts.most_common()` it returns a **new copy** of the internal data structure. Also, every time you call `.residue_contacts` it recreates a new copy of the data as well. What you want is to is to generate them once, and alter the `counter`.
A possible way to do this could be:
(**Disclaimer:** this is untested code and it has been a long time since I last dealt with this codebase)
```python
contacts = ContactTrajectory(traj)
residue_contacts = contacts.residue_contacts #grab the whole list of contact counts
for i in range(nframe):
    pairs = residue_contacts[i].most_common()
    hels = dssp[i]     # information of residue helicity
    for pair, count in pairs:
        r1, r2 = pair[0], pair[0]
        if not (hels[r1.index] == 'H' and hels[r2.index] == 'H'):
            _ = residue_contacts[i].counter.pop(pair)
```

You will have to do it separately for the `residue_contacts` and `atom_contacts` (as those each are independent objects with their own internal counter. Altering them after creation was never an intended use case if I remember correctly) and recreate a ContactTrajectory with:
```python
ContactTrajectory.from_contacts(atom_contacts, residue_contacts, contacts.topology, contacts.query, contacts.haystack, contacts.cutoff, contacts.n_neighbors_ignored)
```

**Comment by wayuer19** [comment] 2023-06-23 12:59
Thank you for your suggestion. I think I have got the expected results with a minor correction.
```
contacts = CT(traj)

atom_contacts = contacts.atom_contacts
for i in range(nframe):
    pairs = atom_contacts[i].most_common()
    hels = dssp[i]
    for pair, count in pairs:
        a1, a2 = pair[0], pair[1]
        r1, r2 = a1.residue.index, a2.residue.index
        if not (hels[r1] == 'H' and hels[r2] == 'H'):
            del atom_contacts[i].counter[frozenset({a1.index, a2.index})]
    pairs = atom_contacts[i].most_common()

residue_contacts = contacts.residue_contacts
for i in range(nframe):
    pairs = residue_contacts[i].most_common()
    hels = dssp[i]
    for pair, count in pairs:
        r1, r2 = pair[0], pair[1]
        if not (hels[r1.index] == 'H' and hels[r2.index] == 'H'):
            del residue_contacts[i].counter[frozenset({r1.index, r2.index})]

hel_contacts = CT.from_contacts(atom_contacts, residue_contacts, contacts.topology, contacts.query, contacts.haystack, contacts.cutoff, contacts.n_neighbors_ignored)
freq = hel_contacts.contact_frequency()
```

Thank you again!

**Comment by sroet** [comment] 2023-06-23 13:10
You are welcome, good luck with the rest of your analysis! I will close this issue as complete, feel free to reopen if that is not the case

**Closed by sroet** 2023-06-23 13:10 UTC
